### ISSUE TITLE
Add SliverGap

### ISSUE THREAD

**Issue by jamesblasco** [letsar/gap#1]
Thanks for this package, it is really useful. I have been something similar to this but your implementation it is way better.

I would like to propose a SliverGap that would behave the same as Gap but for slivers.
Currently the simpler and cleaner way to add a gap between slivers is add a SliverPadding without a child.

**Comment by letsar** [comment]
I also thought about that. I will update this as soon as I have some time. Thanks 👍

**Comment by letsar** [comment]
Added in version 1.1.0

**Comment by jamesblasco** [comment]
That was fast! Thanks man 🙂

**Comment by letsar** [comment]
I finished my job a little earlier today so I was able to take 15mn to do it. If only I had more free time 😅
